return {
	{
		"catppuccin/nvim",
		name = "catppuccin",
		lazy = false,
		priority = 1000,
		config = function()
			require("catppuccin").setup({
				background = {
					light = "latte",
					dark = "mocha",
				},
				color_overrides = {
					mocha = {
						-- Christmas Red: Holly berries, Santa's suit, festive accents
						rosewater = "#e85c5c",
						flamingo = "#d63d3d",
						red = "#c41e3a",
						maroon = "#a01729",

						-- Christmas Green: Pine trees, wreaths, garland
						green = "#5fb865",
						teal = "#7ac77a",
						sky = "#8ed68e",
						sapphire = "#a3e5a3",

						-- Warm Gold: Candlelight, ornaments, stars
						yellow = "#d9a066",
						peach = "#d08770",

						-- Festive Accents: Ribbons, berries
						pink = "#c8956f",
						mauve = "#cc9966",

						-- Winter Blues: Subtle snow shadows, icy accents
						blue = "#83a598",
						lavender = "#8fb4b0",

						-- Warm Cozy Base: Fireplace glow, candlelit room
						text = "#ede4d4",
						subtext1 = "#d5cbb8",
						subtext0 = "#bdb39d",
						overlay2 = "#a39988",
						overlay1 = "#897e6e",
						overlay0 = "#6f6555",
						surface2 = "#3f3933",
						surface1 = "#332e28",
						surface0 = "#29241e",
						base = "#1f1b16",
						mantle = "#181411",
						crust = "#12100d",
					},
				},
				transparent_background = false,
				show_end_of_buffer = false,
				integration_default = false,
				integrations = {
					auto_integrations = true,
				},
				highlight_overrides = {
					all = function(colors)
						return {
							-- UI Elements
							CmpItemMenu = { fg = colors.overlay2 },
							CursorLineNr = { fg = colors.yellow, style = { "bold" } },
							FloatBorder = { bg = colors.base, fg = colors.surface1 },
							GitSignsChange = { fg = colors.peach },
							LineNr = { fg = colors.overlay0 },
							LspInfoBorder = { link = "FloatBorder" },

							-- NvimTree: Christmas file explorer
							NvimTreeFolderName = { fg = colors.green },
							NvimTreeOpenedFolderName = { fg = colors.rosewater, style = { "bold" } },
							NvimTreeGitDeleted = { fg = colors.red },
							NvimTreeGitDirty = { fg = colors.peach },
							NvimTreeIndentMarker = { fg = colors.surface1 },
							NvimTreeNormal = { bg = colors.mantle },
							NvimTreeRootFolder = { fg = colors.yellow, style = { "bold", "italic" } },
							NvimTreeWinSeparator = { fg = colors.surface0, bg = colors.base },
							NvimTreeCursorLine = { bg = colors.surface0 },

							-- Dashboard: Festive welcome
							DashboardHeader = { fg = colors.red, style = { "bold" } },
							DashboardMruTitle = { fg = colors.yellow },
							DashboardProjectTitle = { fg = colors.green },
							DashboardFiles = { fg = colors.text },

							-- Floating windows
							NormalFloat = { bg = colors.base },
							Pmenu = { bg = colors.mantle, fg = "" },
							PmenuSel = { bg = colors.surface0, fg = "" },

							-- Telescope: Enhanced contrast
							TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
							TelescopePreviewNormal = { bg = colors.crust },
							TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
							TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
							TelescopePromptCounter = { fg = colors.yellow, style = { "bold" } },
							TelescopePromptNormal = { bg = colors.surface0 },
							TelescopePromptPrefix = { bg = colors.surface0, fg = colors.red },
							TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
							TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
							TelescopeResultsNormal = { bg = colors.mantle },
							TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
							TelescopeSelection = { bg = colors.surface0, style = { "bold" } },

							VertSplit = { bg = colors.base, fg = colors.surface0 },
							WhichKeyFloat = { bg = colors.mantle },
							YankHighlight = { bg = colors.surface2 },
							FidgetTask = { fg = colors.overlay1 },
							FidgetTitle = { fg = colors.yellow },

							-- Indentation guides
							IblIndent = { fg = colors.surface0 },
							IblScope = { fg = colors.overlay0 },

							-- Syntax: Core language elements
							Boolean = { fg = colors.mauve },
							Number = { fg = colors.mauve },
							Float = { fg = colors.mauve },

							PreProc = { fg = colors.mauve },
							PreCondit = { fg = colors.mauve },
							Include = { fg = colors.red },
							Define = { fg = colors.mauve },
							Conditional = { fg = colors.red },
							Repeat = { fg = colors.red },
							Keyword = { fg = colors.red },
							Typedef = { fg = colors.red },
							Exception = { fg = colors.red },
							Statement = { fg = colors.red },

							Error = { fg = colors.red, style = { "bold" } },
							StorageClass = { fg = colors.peach },
							Tag = { fg = colors.red },
							Label = { fg = colors.peach },
							Structure = { fg = colors.peach },
							Operator = { fg = colors.peach },
							Title = { fg = colors.yellow, style = { "bold" } },
							Special = { fg = colors.yellow },
							SpecialChar = { fg = colors.yellow },
							Type = { fg = colors.yellow, style = { "bold" } },
							Function = { fg = colors.green, style = { "bold" } },
							Delimiter = { fg = colors.overlay1 },
							Ignore = { fg = colors.overlay0 },
							Macro = { fg = colors.teal },

							-- Treesitter: Enhanced Christmas palette
							TSAnnotation = { fg = colors.mauve },
							TSAttribute = { fg = colors.mauve },
							TSBoolean = { fg = colors.mauve },
							TSCharacter = { fg = colors.teal },
							TSCharacterSpecial = { link = "SpecialChar" },
							TSComment = { fg = colors.overlay1, style = { "italic" } },
							TSConditional = { fg = colors.red },
							TSConstBuiltin = { fg = colors.mauve },
							TSConstMacro = { fg = colors.mauve },
							TSConstant = { fg = colors.text },
							TSConstructor = { fg = colors.green },
							TSDebug = { link = "Debug" },
							TSDefine = { link = "Define" },
							TSEnvironment = { link = "Macro" },
							TSEnvironmentName = { link = "Type" },
							TSError = { link = "Error" },
							TSException = { fg = colors.red },
							TSField = { fg = colors.lavender },
							TSFloat = { fg = colors.mauve },
							TSFuncBuiltin = { fg = colors.green },
							TSFuncMacro = { fg = colors.green },
							TSFunction = { fg = colors.green, style = { "bold" } },
							TSFunctionCall = { fg = colors.green },
							TSInclude = { fg = colors.red },
							TSKeyword = { fg = colors.red },
							TSKeywordFunction = { fg = colors.red },
							TSKeywordOperator = { fg = colors.peach },
							TSKeywordReturn = { fg = colors.red, style = { "bold" } },
							TSLabel = { fg = colors.peach },
							TSLiteral = { link = "String" },
							TSMath = { fg = colors.lavender },
							TSMethod = { fg = colors.green, style = { "bold" } },
							TSMethodCall = { fg = colors.green },
							TSNamespace = { fg = colors.yellow },
							TSNone = { fg = colors.text },
							TSNumber = { fg = colors.mauve },
							TSOperator = { fg = colors.peach },
							TSParameter = { fg = colors.text },
							TSParameterReference = { fg = colors.text },
							TSPreProc = { link = "PreProc" },
							TSProperty = { fg = colors.lavender },
							TSPunctBracket = { fg = colors.text },
							TSPunctDelimiter = { fg = colors.overlay1 },
							TSPunctSpecial = { fg = colors.lavender },
							TSRepeat = { fg = colors.red },
							TSStorageClass = { fg = colors.peach },
							TSStorageClassLifetime = { fg = colors.peach },
							TSStrike = { fg = colors.overlay0 },
							TSString = { fg = colors.teal },
							TSStringEscape = { fg = colors.green },
							TSStringRegex = { fg = colors.green },
							TSStringSpecial = { link = "SpecialChar" },
							TSSymbol = { fg = colors.text },
							TSTag = { fg = colors.red },
							TSTagAttribute = { fg = colors.green },
							TSTagDelimiter = { fg = colors.overlay1 },
							TSText = { fg = colors.green },
							TSTextReference = { link = "Constant" },
							TSTitle = { link = "Title" },
							TSTodo = { fg = colors.yellow, bg = colors.surface1, style = { "bold" } },
							TSType = { fg = colors.yellow, style = { "bold" } },
							TSTypeBuiltin = { fg = colors.yellow, style = { "bold" } },
							TSTypeDefinition = { fg = colors.yellow, style = { "bold" } },
							TSTypeQualifier = { fg = colors.peach, style = { "bold" } },
							TSURI = { fg = colors.lavender, style = { "underline" } },
							TSVariable = { fg = colors.text },
							TSVariableBuiltin = { fg = colors.mauve },

							-- Modern @ syntax mappings
							["@annotation"] = { link = "TSAnnotation" },
							["@attribute"] = { link = "TSAttribute" },
							["@boolean"] = { link = "TSBoolean" },
							["@character"] = { link = "TSCharacter" },
							["@character.special"] = { link = "TSCharacterSpecial" },
							["@comment"] = { link = "TSComment" },
							["@conceal"] = { link = "Grey" },
							["@conditional"] = { link = "TSConditional" },
							["@constant"] = { link = "TSConstant" },
							["@constant.builtin"] = { link = "TSConstBuiltin" },
							["@constant.macro"] = { link = "TSConstMacro" },
							["@constructor"] = { link = "TSConstructor" },
							["@debug"] = { link = "TSDebug" },
							["@define"] = { link = "TSDefine" },
							["@error"] = { link = "TSError" },
							["@exception"] = { link = "TSException" },
							["@field"] = { link = "TSField" },
							["@float"] = { link = "TSFloat" },
							["@function"] = { link = "TSFunction" },
							["@function.builtin"] = { link = "TSFuncBuiltin" },
							["@function.call"] = { link = "TSFunctionCall" },
							["@function.macro"] = { link = "TSFuncMacro" },
							["@include"] = { link = "TSInclude" },
							["@keyword"] = { link = "TSKeyword" },
							["@keyword.function"] = { link = "TSKeywordFunction" },
							["@keyword.operator"] = { link = "TSKeywordOperator" },
							["@keyword.return"] = { link = "TSKeywordReturn" },
							["@label"] = { link = "TSLabel" },
							["@math"] = { link = "TSMath" },
							["@method"] = { link = "TSMethod" },
							["@method.call"] = { link = "TSMethodCall" },
							["@namespace"] = { link = "TSNamespace" },
							["@none"] = { link = "TSNone" },
							["@number"] = { link = "TSNumber" },
							["@operator"] = { link = "TSOperator" },
							["@parameter"] = { link = "TSParameter" },
							["@parameter.reference"] = { link = "TSParameterReference" },
							["@preproc"] = { link = "TSPreProc" },
							["@property"] = { link = "TSProperty" },
							["@punctuation.bracket"] = { link = "TSPunctBracket" },
							["@punctuation.delimiter"] = { link = "TSPunctDelimiter" },
							["@punctuation.special"] = { link = "TSPunctSpecial" },
							["@repeat"] = { link = "TSRepeat" },
							["@storageclass"] = { link = "TSStorageClass" },
							["@storageclass.lifetime"] = { link = "TSStorageClassLifetime" },
							["@strike"] = { link = "TSStrike" },
							["@string"] = { link = "TSString" },
							["@string.escape"] = { link = "TSStringEscape" },
							["@string.regex"] = { link = "TSStringRegex" },
							["@string.special"] = { link = "TSStringSpecial" },
							["@symbol"] = { link = "TSSymbol" },
							["@tag"] = { link = "TSTag" },
							["@tag.attribute"] = { link = "TSTagAttribute" },
							["@tag.delimiter"] = { link = "TSTagDelimiter" },
							["@text"] = { link = "TSText" },
							["@text.danger"] = { link = "TSDanger" },
							["@text.diff.add"] = { link = "diffAdded" },
							["@text.diff.delete"] = { link = "diffRemoved" },
							["@text.emphasis"] = { link = "TSEmphasis" },
							["@text.environment"] = { link = "TSEnvironment" },
							["@text.environment.name"] = { link = "TSEnvironmentName" },
							["@text.literal"] = { link = "TSLiteral" },
							["@text.math"] = { link = "TSMath" },
							["@text.note"] = { link = "TSNote" },
							["@text.reference"] = { link = "TSTextReference" },
							["@text.strike"] = { link = "TSStrike" },
							["@text.strong"] = { link = "TSStrong" },
							["@text.title"] = { link = "TSTitle" },
							["@text.todo"] = { link = "TSTodo" },
							["@text.todo.checked"] = { link = "Green" },
							["@text.todo.unchecked"] = { link = "Ignore" },
							["@text.underline"] = { link = "TSUnderline" },
							["@text.uri"] = { link = "TSURI" },
							["@text.warning"] = { link = "TSWarning" },
							["@todo"] = { link = "TSTodo" },
							["@type"] = { link = "TSType" },
							["@type.builtin"] = { link = "TSTypeBuiltin" },
							["@type.definition"] = { link = "TSTypeDefinition" },
							["@type.qualifier"] = { link = "TSTypeQualifier" },
							["@uri"] = { link = "TSURI" },
							["@variable"] = { link = "TSVariable" },
							["@variable.builtin"] = { link = "TSVariableBuiltin" },

							-- LSP semantic tokens
							["@lsp.type.class"] = { link = "TSType" },
							["@lsp.type.comment"] = { link = "TSComment" },
							["@lsp.type.decorator"] = { link = "TSFunction" },
							["@lsp.type.enum"] = { link = "TSType" },
							["@lsp.type.enumMember"] = { link = "TSProperty" },
							["@lsp.type.events"] = { link = "TSLabel" },
							["@lsp.type.function"] = { link = "TSFunction" },
							["@lsp.type.interface"] = { link = "TSType" },
							["@lsp.type.keyword"] = { link = "TSKeyword" },
							["@lsp.type.macro"] = { link = "TSConstMacro" },
							["@lsp.type.method"] = { link = "TSMethod" },
							["@lsp.type.modifier"] = { link = "TSTypeQualifier" },
							["@lsp.type.namespace"] = { link = "TSNamespace" },
							["@lsp.type.number"] = { link = "TSNumber" },
							["@lsp.type.operator"] = { link = "TSOperator" },
							["@lsp.type.parameter"] = { link = "TSParameter" },
							["@lsp.type.property"] = { link = "TSProperty" },
							["@lsp.type.regexp"] = { link = "TSStringRegex" },
							["@lsp.type.string"] = { link = "TSString" },
							["@lsp.type.struct"] = { link = "TSType" },
							["@lsp.type.type"] = { link = "TSType" },
							["@lsp.type.typeParameter"] = { link = "TSTypeDefinition" },
							["@lsp.type.variable"] = { link = "TSVariable" },
						}
					end,
				},
			})
			vim.cmd("colorscheme catppuccin")
		end,
	},
}
